baseURL = 'https://sauvikbiswas.com/'
languageCode = 'en-us'
title = 'Sauvik Biswas'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
paginationSize = 100
colorPalette = 'base16-eighties'

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"
