baseURL = 'https://sauvikbiswas.com/'
languageCode = 'en-us'
title = 'Sauvik Biswas'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
paginationSize = 100
colorPalette = 'base16-eighties'

[params.breadcrumbs]
enabled = false

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "works"
url = "/works"

[[params.menu]]
name = "travelogue"
url = "/travelogue"

[[params.menu]]
name = "comics"
url = "/comics"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "now"
url = "/now"

[markup]
[markup.goldmark]
renderer.unsafe = true